[providers]
nixpacks = true

[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = ['pnpm run build']

[start]
cmd = 'pnpm exec serve -s dist -l ${PORT}'

