[build]
builder = "NIXPACKS"

[deploy]
startCommand = "pnpm exec serve -s dist -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = ['pnpm run build']

